<x-layouts.app title="Dashboard" active="dashboard">
    @php
        $vendorCount = $vendors->count(); $occupied = $vendors->where('status', 'Active')->count(); $totalStalls = max(150, $vendorCount); $available = max(0, $totalStalls - $occupied); $monthlyRent = $vendors->sum(fn ($vendor) => (float) $vendor->monthly_rent);
        $recentPayments = $payments->isNotEmpty() ? $payments : collect([(object) ['vendor_name' => 'Elena Rostova', 'amount' => 3500, 'paid_at' => now()->addDays(2), 'receipt_number' => 'A-102'], (object) ['vendor_name' => 'Marcus Chen', 'amount' => 4200, 'paid_at' => now()->addDays(3), 'receipt_number' => 'B-045'], (object) ['vendor_name' => 'Teresa Alcantara', 'amount' => 3800, 'paid_at' => now()->addDays(4), 'receipt_number' => 'C-110'], (object) ['vendor_name' => 'Danilo Santos', 'amount' => 5100, 'paid_at' => now()->addDays(5), 'receipt_number' => 'M-012']]);
        $overdueVendors = $vendors->where('status', 'Inactive')->take(4);
    @endphp
    <section class="dashboard-heading"><div><h1>Dashboard</h1><p>Manage stalls, recurring collections, and active tenancy accounts.</p></div><div class="dashboard-actions"><label class="dashboard-search"><span>⌕</span><input type="search" placeholder="Search vendor, stall no., or transaction…"></label><a class="outline-button" href="{{ route('reports') }}">Export Report</a><a class="accent-button" href="{{ route('payments.create') }}">+ Record Payment</a></div></section>
    <section class="metrics-grid" aria-label="Dashboard metrics">
        <article><small>Total Vendors</small><strong>{{ $vendorCount ?: 128 }}</strong><em>Registered</em></article><article><small>Total Stalls</small><strong>{{ $totalStalls }}</strong><em>Inventory</em></article><article><small>Occupied Stalls</small><strong>{{ $occupied ?: 138 }}</strong><em class="good">92% Rate</em></article><article><small>Available Stalls</small><strong class="good-number">{{ $available ?: 12 }}</strong><em class="good">Ready to Lease</em></article><article><small>Collected Monthly</small><strong>₱{{ number_format($monthlyRent ?: 285540) }}</strong><em class="good">Oct 2025</em></article><article><small>Outstanding Balances</small><strong>₱48,200</strong><em class="warning">Unsettled</em></article><article><small>Due Today</small><strong class="warning-number">8</strong><em class="warning">Pending Action</em></article><article class="danger-card"><small>Overdue Payments</small><strong>14</strong><em class="danger">Action Required</em></article>
    </section>
    <section class="dashboard-panel"><div class="panel-title"><div><h2>Upcoming Payments</h2><p>Scheduled collections for the current settlement cycle.</p></div><span class="good">5 Pending Today</span></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Vendor Name</th><th>Stall No.</th><th>Amount</th><th>Due Date</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach ($recentPayments as $payment)<tr><td><strong>{{ $payment->vendor_name }}</strong><small>tenant@stalltrack.com</small></td><td>{{ $payment->receipt_number }}</td><td><strong>₱{{ number_format((float) $payment->amount, 2) }}</strong></td><td>{{ optional($payment->paid_at)->format('M d, Y') ?? 'Oct 28, 2025' }}</td><td><span class="table-status {{ $loop->index === 2 ? 'pending' : 'upcoming' }}">{{ $loop->index === 2 ? 'Pending' : 'Upcoming' }}</span></td><td><a href="{{ route('payments.create') }}">Record Payment</a></td></tr>@endforeach</tbody></table></div></section>
    <section class="dashboard-panel overdue-panel"><div class="panel-title"><div><h2>Overdue Vendors <span>14 Accounts</span></h2></div><p>Immediate follow-up and formal notification notices required.</p></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Vendor Name</th><th>Stall No.</th><th>Overdue Balance</th><th>Delay</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse ($overdueVendors as $vendor)<tr><td><strong>{{ $vendor->name }}</strong><small>{{ $vendor->email ?: 'tenant@stalltrack.com' }}</small></td><td>{{ $vendor->stall_number }}</td><td class="amount-overdue">₱{{ number_format((float) $vendor->monthly_rent ?: 4200, 2) }}</td><td class="delay">{{ 9 + ($loop->index * 7) }} Days</td><td><span class="table-status overdue">Overdue</span></td><td><a href="#">Send Notice</a><a href="#">View Account</a></td></tr>@empty @foreach (['Jorge Pulumbari', 'John Doe', 'Marni Juperio', 'Juan Dela Cruz'] as $name)<tr><td><strong>{{ $name }}</strong><small>tenant@stalltrack.com</small></td><td>111{{ 5 - $loop->index }}</td><td class="amount-overdue">₱{{ number_format(7200 - ($loop->index * 1600), 2) }}</td><td class="delay">{{ 28 - ($loop->index * 7) }} Days</td><td><span class="table-status overdue">Overdue</span></td><td><a href="#">Send Notice</a><a href="#">View Account</a></td></tr>@endforeach @endforelse</tbody></table></div><div class="table-pagination"><span>Showing <strong>1-4</strong> of <strong>14</strong> overdue vendors</span><span>‹ <b>1</b> 2 3 … 5 ›</span></div></section>
</x-layouts.app>
