<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vendor Dashboard · Public Market</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="vendor-dashboard">
    @php($vendorPayments = $payments ?? collect())
    <aside class="vendor-sidebar">
        <div class="vendor-brand">Public Market <small>VENDOR PORTAL</small></div>
        <nav><a class="selected" href="{{ route('vendor.dashboard') }}">▣ &nbsp; Overview</a><a href="{{ route('vendor.dashboard') }}#lease">▤ &nbsp; My Stall &amp; Lease</a><a href="{{ route('vendor.dashboard') }}#payments">▥ &nbsp; Payment &amp; Docs</a><a href="{{ route('vendor.dashboard') }}#notices">▧ &nbsp; Notices &amp; Announcements</a></nav>
        <div class="vendor-sidebar-bottom"><a href="#support">◌ &nbsp; Market Support</a><a href="#account">◉ &nbsp; Account Settings</a><span class="vendor-status">STATUS <b>● Active Vendor</b></span></div>
    </aside>
    <main class="vendor-main">
        <header class="vendor-topbar"><div class="vendor-search">⌕ <span>Search dues, permits, notices...</span></div><div class="verified">● &nbsp; Permit Verified:<strong> 2024–2027</strong></div><a class="pay-button" href="#payments">▣ &nbsp; Pay Due / Upload Proof</a><span class="top-icon">♧</span><div class="vendor-user"><span class="user-avatar">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</span><strong>{{ auth()->user()->name }}</strong><small>Stall A14-14</small></div></header>
        <div class="vendor-content">
            <div class="vendor-breadcrumb">STALL  A-14 · MUNICIPAL MARKET &nbsp; <b>Lease Active · 2026</b></div>
            <section class="vendor-intro"><div><h1>Welcome back, {{ explode(' ', auth()->user()->name)[0] }}</h1><p>Dry Goods &amp; Fresh Produce Section · Lease Agreement valid until Dec 31, 2026</p></div><div class="intro-actions"><button>▣ &nbsp; Download Statement</button><a href="#payments">Pay Current Due&nbsp; →</a></div></section>
            <div class="vendor-grid">
                <div class="vendor-primary">
                    <div class="vendor-stat-grid"><article><label>CURRENT BALANCE</label><strong>₱1,200.00</strong><small>Deadline: Aug 30, 2026</small></article><article><label>DUE IN</label><strong>₱1,200.00</strong><small>Next cycle: Sep 01, 2026</small></article><article><label>MONTHLY STALL RENT</label><strong>₱1,200.00</strong><small>Next cycle: Sep 01, 2026</small></article><article class="green-stat"><label>STALL STATUS</label><strong>Active &amp; Inspected</strong><small>Sanitation Passed Aug 15</small></article><article><label>PAST 12 MONTHS</label><strong>₱9,600.00</strong><small>6 payments on file</small></article></div>
                    <div class="due-notice"><span>▧</span><div><strong>August 2026 Stall Rent is Due</strong><p>Your monthly rental fee of ₱1,200.00 expires on August 30, 2026. Please settle on schedule to avoid service interruption.</p></div><a href="#payments">Pay Now&nbsp; →</a></div>
                    @if (session('success')) <div class="vendor-success">{{ session('success') }}</div> @endif
                    <section class="vendor-card vendor-payment-card" id="payments"><div class="card-heading"><div><h2>Submit Vendor Payment</h2><p>Send your latest payment details to Market Treasury for verification.</p></div></div><form method="POST" action="{{ route('vendor.payments.store') }}" class="vendor-payment-form">@csrf<div><label for="vendor-payment-amount">Amount paid</label><div class="vendor-money-input"><span>₱</span><input id="vendor-payment-amount" name="amount" type="number" min="0.01" step="0.01" placeholder="1,200.00" required></div></div><div><label for="vendor-payment-date">Payment date</label><input id="vendor-payment-date" name="paid_at" type="date" value="{{ now()->format('Y-m-d') }}" required></div><div><label for="vendor-payment-receipt">Receipt number</label><input id="vendor-payment-receipt" name="receipt_number" placeholder="OR-0063" required></div><button type="submit">Submit Payment <span>→</span></button></form></section>
                    <section class="vendor-card" id="payment-history"><div class="card-heading"><div><h2>Payment &amp; Billing History</h2><p>Verified official electronic receipts recorded by Market Treasury</p></div><label>FILTER: <select><option>Year 2026 (All)</option></select></label></div><table class="billing-table"><thead><tr><th>RECEIPT</th><th>DATE</th><th>AMOUNT</th><th>METHOD</th><th>STATUS</th></tr></thead><tbody>@forelse ($vendorPayments as $payment)<tr><td>{{ $payment->receipt_number }}</td><td>{{ $payment->paid_at->format('M d, Y') }}</td><td>₱{{ number_format((float) $payment->amount, 2) }}</td><td>Vendor submission</td><td><b>Pending review</b></td></tr>@empty<tr><td>OR-0062</td><td>Aug 26, 2026</td><td>₱1,200.00</td><td>Cash / Bank</td><td><b>Verified</b></td></tr><tr><td>OR-0061</td><td>Jul 28, 2026</td><td>₱1,200.00</td><td>GCash / Maya</td><td><b>Verified</b></td></tr><tr><td>OR-0060</td><td>Jun 25, 2026</td><td>₱1,200.00</td><td>Cash / Bank</td><td><b>Verified</b></td></tr><tr><td>OR-0059</td><td>May 27, 2026</td><td>₱1,200.00</td><td>Transfer</td><td><b>Verified</b></td></tr>@endforelse</tbody></table><div class="billing-footer">Showing last {{ $vendorPayments->count() ?: 4 }} transactions <a href="#payment-history">View full billing archive &amp; tax receipts →</a></div></section>
                    <section class="vendor-card lease-card" id="lease"><div class="card-heading"><div><h2>Stall Specifications &amp; Lease Agreement</h2><p>Official municipal registry records and utility submeters</p></div><code>UNIT ID: ST-A14</code></div><div class="lease-details"><div><label>STALL ID · UNIT</label><strong>Stall A-14 · Corner Unit</strong><small>16.5 sq. meters (4m × 4m) · Commercial Zone</small></div><div><label>SECTION CLASSIFICATION</label><strong>Wet &amp; Dry Goods · Section A</strong><small>Category: Fresh Vegetables &amp; Grains Retail</small></div><div><label>SUBMETER UTILITY READINGS</label><strong>Water: 00412 · Power: 0381 kWh</strong></div><div><label>LEASE VALIDITY PERIOD</label><strong>Jan 01, 2024 – Dec 31, 2026</strong><small class="warning">Eligible for 3-year renewal after lease ends</small></div></div><div class="stall-photo"><div>Stall A-14 Physical Registry View</div><small>Expected Market Standards &amp; Safety Division</small></div></section>
                </div>
                <aside class="vendor-right"><section class="contact-card" id="support"><h2>Assigned Collector</h2><p>Direct officer for dues collection &amp; compliance check</p><div class="collector"><span>JR</span><div><strong>J. Ramos</strong><small>Rent Collector<br>City Hall Hours:<br>8:00 AM – 4:00 PM</small></div></div><p><b>Market:</b> 2nd Floor, Market Admin Office</p><p><b>Office:</b> (084) 216–9080</p><p><b>Sanitation:</b> Dr. Ms. Santos, Officer Unit</p><a href="#support">♧ &nbsp; Submit Stall Inquiry / Maintenance</a></section><section class="contact-card" id="notices"><h2>Important Vendor Rule</h2><p>All stalls must display their official Mayor’s Permit 2026 copy on the front stall barrier. Maintain aisle clearance of at least 1.2 meters at all trading hours.</p></section></aside>
            </div>
        </div>
    </main>
</body>
</html>
