<x-layouts.app title="Rental Management" active="rentals">
    @php
        $rentals = [
            ['ref' => 'CTR-2024-A102', 'vendor' => 'Elena Santos Rostova', 'business' => 'Rostova Fresh Produce', 'stall' => 'Stall A-102', 'type' => 'Wet Market', 'rate' => 3500, 'frequency' => 'Monthly', 'term' => 'Nov 01, 2024', 'due' => 'Due Nov 28, 2025', 'status' => 'Active'],
            ['ref' => 'CTR-2024-B045', 'vendor' => 'Marcus Chen', 'business' => 'Chen Grocers', 'stall' => 'Stall B-045', 'type' => 'Dry Goods', 'rate' => 4200, 'frequency' => 'Monthly', 'term' => 'Jan 15, 2024', 'due' => 'Due Dec 05, 2025', 'status' => 'Active'],
            ['ref' => 'CTR-2023-M012', 'vendor' => 'Danilo Santos', 'business' => 'Santos Meats Depot', 'stall' => 'Stall M-012', 'type' => 'Cold Storage', 'rate' => 2800, 'frequency' => 'Bi-weekly', 'term' => 'Mar 01, 2023', 'due' => 'Exp: Dec 12, 2024', 'status' => 'Expiring Soon'],
            ['ref' => 'CTR-2024-C110', 'vendor' => 'Teresa Alcantara', 'business' => 'Alcantara Apparel', 'stall' => 'Stall C-110', 'type' => 'Retail Pavilion', 'rate' => 2500, 'frequency' => 'Monthly', 'term' => 'Feb 10, 2024', 'due' => 'Due Jan 31, 2026', 'status' => 'Active'],
            ['ref' => 'CTR-2022-F008', 'vendor' => 'Lourdes Bautista', 'business' => 'Floral Pavilion Craft', 'stall' => 'Stall F-008', 'type' => 'Dry Goods', 'rate' => 1800, 'frequency' => 'Weekly', 'term' => 'May 01, 2022', 'due' => 'Expired Oct 31, 2024', 'status' => 'Expired'],
            ['ref' => 'CTR-2023-D005', 'vendor' => 'Rafael Gomez', 'business' => 'Kusinа Foods & Grill', 'stall' => 'Stall D-005', 'type' => 'Food Court', 'rate' => 5000, 'frequency' => 'Monthly', 'term' => 'Sep 01, 2023', 'due' => 'Term: Aug 14, 2024', 'status' => 'Terminated'],
        ];
    @endphp

    <div class="rental-management-page">
        <div class="rental-breadcrumb">Operational Authority &gt; Tenancy &amp; Leases &gt; <strong>Active Rental Agreements</strong></div>
        <section class="rental-heading"><div><h1>Rental Management</h1><p>Connect and monitor active tenant contracts, stall leases, rental rates, and payment frequencies.</p></div><div><a class="rental-filter-button" href="{{ route('reports') }}">⇩ Filter &amp; Export</a><a class="rental-new-button" href="{{ route('vendors.index') }}#add-vendor">＋ New Rental Contract</a></div></section>
        <section class="rental-summary-grid"><article><small>TOTAL ACTIVE LEASES</small><strong>138</strong><span>92% Occupancy</span><i>▣</i></article><article><small>EXPIRING CONTRACTS</small><strong>9</strong><span>Within 30 Days</span><i>◷</i></article><article><small>MONTHLY RENTAL VOLUME</small><strong class="rental-blue">₱485,200</strong><span>↗ 3.4% MoM</span><i>▣</i></article><article><small>EXPIRED / TERMINATED</small><strong>6</strong><span>Archived</span><i>◌</i></article></section>
        <form class="rental-filter-bar" id="rental-filter-form"><label><span>⌕</span><input id="rental-search" type="search" placeholder="Search contract #, vendor name, or stall number..."></label><select id="rental-status"><option value="">Status: &nbsp; All Statuses</option><option>Active</option><option>Expiring Soon</option><option>Expired</option><option>Terminated</option></select><select id="rental-frequency"><option value="">Frequency: &nbsp; All Frequencies</option><option>Monthly</option><option>Bi-weekly</option><option>Weekly</option></select><button type="reset">◌ Reset</button></form>
        <section class="rental-table-card"><div class="rental-table-scroll"><table class="rental-table" id="rental-table"><thead><tr><th>Contract Ref #</th><th>Vendor &amp; Business</th><th>Stall</th><th>Rental Rate</th><th>Frequency</th><th>Term / Due Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach ($rentals as $rental)<tr data-search="{{ strtolower($rental['ref'].' '.$rental['vendor'].' '.$rental['stall'].' '.$rental['business']) }}" data-status="{{ $rental['status'] }}" data-frequency="{{ $rental['frequency'] }}"><td><b class="rental-ref">{{ $rental['ref'] }}</b></td><td><strong>{{ $rental['vendor'] }}</strong><small>{{ $rental['business'] }}</small></td><td><strong>{{ $rental['stall'] }}</strong><small>{{ $rental['type'] }}</small></td><td><strong>₱{{ number_format($rental['rate'], 2) }}</strong></td><td><span class="frequency-pill">{{ $rental['frequency'] }}</span></td><td>{{ $rental['term'] }}<small>{{ $rental['due'] }}</small></td><td><span class="rental-status-pill {{ strtolower(str_replace(' ', '-', $rental['status'])) }}">● {{ $rental['status'] }}</span></td><td><a href="{{ route('vendors.index') }}">{{ in_array($rental['status'], ['Expired', 'Terminated']) ? 'Archive' : ($rental['status'] === 'Expiring Soon' ? 'Renew' : 'Details') }}</a> &nbsp; ✎</td></tr>@endforeach</tbody></table></div><div class="rental-table-footer">Showing <span id="rental-visible-count">6</span> of 144 agreements <span><button type="button" disabled>‹</button><button type="button" class="current">1</button><button type="button">2</button><button type="button">3</button><span>…</span><button type="button">24</button><button type="button">›</button></span></div></section>
    </div>
    <script>
        const rentalRows = [...document.querySelectorAll('#rental-table tbody tr')];
        const rentalPerPage = 4;
        let rentalPage = 1;
        const rentalSearch = document.querySelector('#rental-search');
        const rentalStatus = document.querySelector('#rental-status');
        const rentalFrequency = document.querySelector('#rental-frequency');
        const rentalButtons = [...document.querySelectorAll('.rental-table-footer button')];
        const rentalPrev = rentalButtons[0];
        const rentalNext = rentalButtons[rentalButtons.length - 1];
        rentalButtons.slice(1, -1).forEach((button, index) => { button.classList.add('rental-page-button'); button.dataset.page = index + 1; });
        function filterRentals() { const query = rentalSearch.value.toLowerCase().trim(); const status = rentalStatus.value; const frequency = rentalFrequency.value; const matchingRows = rentalRows.filter(row => (!query || row.dataset.search.includes(query)) && (!status || row.dataset.status === status) && (!frequency || row.dataset.frequency === frequency)); const lastPage = Math.max(1, Math.ceil(matchingRows.length / rentalPerPage)); rentalPage = Math.min(rentalPage, lastPage); rentalRows.forEach(row => { row.hidden = !matchingRows.includes(row) || matchingRows.indexOf(row) < (rentalPage - 1) * rentalPerPage || matchingRows.indexOf(row) >= rentalPage * rentalPerPage; }); document.querySelector('#rental-visible-count').textContent = matchingRows.length; document.querySelectorAll('.rental-page-button').forEach(button => { const page = Number(button.dataset.page); button.hidden = page > lastPage; button.classList.toggle('current', page === rentalPage); }); rentalPrev.disabled = rentalPage === 1; rentalNext.disabled = rentalPage === lastPage; }
        rentalSearch.addEventListener('input', () => { rentalPage = 1; filterRentals(); }); rentalStatus.addEventListener('change', () => { rentalPage = 1; filterRentals(); }); rentalFrequency.addEventListener('change', () => { rentalPage = 1; filterRentals(); }); document.querySelector('#rental-filter-form').addEventListener('reset', () => setTimeout(() => { rentalPage = 1; filterRentals(); })); rentalPrev.addEventListener('click', () => { rentalPage -= 1; filterRentals(); }); rentalNext.addEventListener('click', () => { rentalPage += 1; filterRentals(); }); document.querySelectorAll('.rental-page-button').forEach(button => button.addEventListener('click', () => { rentalPage = Number(button.dataset.page); filterRentals(); })); filterRentals();
    </script>
</x-layouts.app>
