<x-layouts.admin title="Edit Vendor" active="vendors">
    <div class="form-back"><a href="{{ route('vendors.show', $vendor) }}">← Back to vendor account</a></div>
    <section class="page-heading"><h1>Edit Vendor Details</h1><p>Update the vendor profile and their linked stall and rental information.</p></section>
    @if ($errors->any())<div class="form-alert">Please correct the highlighted fields.</div>@endif
    <section class="form-panel max-w-4xl"><form class="portal-form" method="POST" action="{{ route('vendors.update', $vendor) }}">@csrf @method('PUT')
        <div class="form-grid"><label class="field">Full name<input name="name" value="{{ old('name', $vendor->name) }}" required></label><label class="field">Email<input name="email" type="email" value="{{ old('email', $vendor->email) }}"></label></div>
        <div class="form-grid"><label class="field">Contact number<input name="contact_number" value="{{ old('contact_number', $vendor->contact_number) }}"></label><label class="field">Status<select name="status"><option value="Active" @selected(old('status', $vendor->status) === 'Active')>Active</option><option value="Inactive" @selected(old('status', $vendor->status) === 'Inactive')>Inactive</option></select></label></div>
        <label class="field">Residential address<textarea name="residential_address">{{ old('residential_address', $vendor->residential_address) }}</textarea></label>
        <div class="form-grid"><label class="field">Linked stall number<input name="stall_number" value="{{ old('stall_number', $vendor->stall_number) }}" required></label><label class="field">Market section<input name="market_section" value="{{ old('market_section', $vendor->market_section) }}" required></label></div>
        <div class="form-grid"><label class="field">Rental rate<input name="monthly_rent" type="number" min="0" step="0.01" value="{{ old('monthly_rent', $vendor->monthly_rent) }}" required></label><label class="field">Billing cycle<select name="billing_cycle"><option value="Monthly" @selected(old('billing_cycle', $vendor->billing_cycle) === 'Monthly')>Monthly</option><option value="Quarterly" @selected(old('billing_cycle', $vendor->billing_cycle) === 'Quarterly')>Quarterly</option></select></label></div>
        <div class="form-grid"><label class="field">Contract start<input name="contract_start_date" type="date" value="{{ old('contract_start_date', $vendor->contract_start_date?->toDateString()) }}" required></label><label class="field">Contract end<input name="contract_end_date" type="date" value="{{ old('contract_end_date', $vendor->contract_end_date?->toDateString()) }}" required></label></div>
        <div class="form-actions"><a href="{{ route('vendors.show', $vendor) }}">Cancel</a><button class="black-button" type="submit">Save changes</button></div>
    </form></section>
</x-layouts.admin>
